version: "3.9"
networks:
  backend:
    driver: bridge
services:
  php:
    build: ./php
    volumes:
      - ../laravel:/var/www/html
    depends_on:
      - mysql
    networks:
      - backend
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../laravel:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - backend
